[package]
name = "abagames-util"
version = "0.1.0"
authors = ["Ben Boeckel <mathstuf@gmail.com>"]
readme = "README>md"
license = "BSD-2-Clause"

[dependencies]
chrono = "~0.2"
mersenne_twister = "~0.3"
nalgebra = "~0.10"
rand = "~0.3"
sdl2 = "~0.18"
sdl2_mixer = "~0.17"
