[package]
name = "abagames-util"
version = "0.1.0"
authors = ["Ben Boeckel <mathstuf@gmail.com>"]
readme = "README>md"
license = "BSD-2-Clause"

[dependencies]
cgmath = "~0.12"
chrono = "~0.2"
gfx = { git = "https://github.com/gfx-rs/gfx" }
gfx_device_gl = { git = "https://github.com/gfx-rs/gfx" }
gfx_window_sdl = { git = "https://github.com/gfx-rs/gfx" }
itertools = "~0.5"
mersenne_twister = "~0.3"
rand = "~0.3"
sdl2 = "~0.23"
sdl2_mixer = "~0.23"
