[package]
name = "abagames-util"
version = "0.1.0"
authors = ["Ben Boeckel <mathstuf@gmail.com>"]
readme = "README>md"
license = "BSD-2-Clause"

[dependencies]
cgmath = "~0.12"
chrono = "~0.2"
gfx = "~0.12"
gfx_device_gl = "~0.11"
gfx_window_sdl = "~0.3"
itertools = "~0.5"
mersenne_twister = "~0.3"
rand = "~0.3"
sdl2 = "~0.18"
sdl2_mixer = "~0.17"
